title: Mingxiang's blog
email: mingxiangxue@gmail.com
description: >-
  A blog that contains articles about programming languages, open source
  frameworks, and some technical how-to and tricks.
url: "https://uzxmx.github.io"
github_username: uzxmx
permalink: /:title:output_ext

remote_theme: "mmistakes/minimal-mistakes@4.19.1"
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

comments:
  provider: "custom"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-164919405-1"

google_site_verification: "4cV_DkFkOihbmPCkF3LqIVBC3lM0yA0UhentAgp7Mmg"
bing_site_verification: "E2FD20A4199C5CDBE9E4842CCD5820E0"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
      read_time: true
      comments: true
